-- CREATE TABLE CDM.DM_SETTLEMENT_REPORT 
-- (
--     ID SERIAL NOT NULL,
--     RESTAURANT_ID VARCHAR NOT NULL,
--     RESTAURANT_NAME VARCHAR NOT NULL,
--     SETTLEMENT_DATE DATE NOT NULL,
--     ORDERS_COUNT INTEGER NOT NULL,
--     ORDERS_TOTAL_SUM NUMERIC(14,2) NOT NULL,
--     ORDERS_BONUS_PAYMENT_SUM NUMERIC(14,2) NOT NULL,
--     ORDERS_BONUS_GRANTED_SUM NUMERIC(14,2) NOT NULL,
--     ORDER_PROCESSING_FEE NUMERIC(14,2) NOT NULL,
--     RESTAURANT_REWARD_SUM NUMERIC(14,2) NOT NULL
-- )
-- ALTER TABLE CDM.DM_SETTLEMENT_REPORT ADD CONSTRAINT SETTLEMENT_REPORT_PK PRIMARY KEY(ID)
ALTER TABLE CDM.DM_SETTLEMENT_REPORT ADD CONSTRAINT dm_settlement_report_settlement_date_check 
CHECK (SETTLEMENT_DATE >= date'2022-01-01' and SETTLEMENT_DATE < date'2500-01-01')